spring.datasource.url=jdbc:postgresql://localhost:5432/recommendation_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.rules.datasource.url=jdbc:postgresql://localhost:5432/rules_db
spring.rules.datasource.username=postgres
spring.rules.datasource.password=password
spring.rules.datasource.driver-class-name=org.postgresql.Driver